### ISSUE TITLE
Make it easier for contributors to work on website

### ISSUE THREAD

**Issue by gsong** [Techtonica/techtonica.org#175]
* [x] Don't require them to have secrets (discuss in #178)
* [x] Make sure it's clear how to spin up the local development environment (I think this is large done, @vegetabill do you feel like there's anything additional we need to do here, from your experience?)
* [x] Make the coding standard clear, ideally via pre-commit hooks (#176)
* [x] Have a clear branch management and tagging strategy, especially with regards to release (discuss in #177)

**Comment by rogue0137** [comment]
@gsong "don't require them to have secrets" should be taken care of my handling eventbrite exceptions; let's work on getting the branch info into the readme and then we can close this issue

**Comment by gsong** [comment]
@rogue0137 I believe @celinaye has volunteered to get branching strategy incorporated into documentation: https://techtonicaorg.slack.com/archives/C426YQP60/p1596500987008100?thread_ts=1596479105.006800&cid=C426YQP60

**Comment by krokoschke** [comment]
https://github.com/Techtonica/techtonica.org/commit/08788222d7acdd6f829dd30ee621119b6b57063a
Updated the README w clear structured Branch management
